-- 测试环境专用数据库脚本。
--
-- 文件名保留为 schema.sql，是为了在测试 classpath 中覆盖生产环境同名脚本，
-- 防止 H2 误加载仅面向 MySQL 的全量建表语句。生产打包不会包含本文件。
DROP TABLE IF EXISTS execution_record;
CREATE TABLE execution_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_id BIGINT NOT NULL,
    input_data CLOB,
    output_data CLOB,
    status VARCHAR(50) NOT NULL,
    node_results CLOB,
    error_message CLOB,
    duration INT,
    worker_id VARCHAR(100),
    heartbeat_at TIMESTAMP,
    cancel_requested TINYINT DEFAULT 0,
    queued_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    attempt INT DEFAULT 0,
    idempotency_key VARCHAR(100),
    execution_mode VARCHAR(30),
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0
);

DROP TABLE IF EXISTS execution_outbox;
CREATE TABLE execution_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL,
    queue_key VARCHAR(200) NOT NULL,
    payload CLOB NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempts INT DEFAULT 0,
    next_attempt_at TIMESTAMP,
    last_error VARCHAR(1000),
    sent_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
